name: .NET
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Set Version
      run: |
        VERSION="1.0.${{ github.run_number }}"
        echo "Building version: $VERSION"
        sed -i "s/<Version>[0-9]\+\.[0-9]\+\.[0-9]\+<\/Version>/<Version>$VERSION<\/Version>/" Agdir.GlobalFieldId/Agdir.GlobalFieldId.csproj
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release
    
    - name: Test
      run: dotnet test --no-build --verbosity normal  --configuration Release

    - name: Pack
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: dotnet pack Agdir.GlobalFieldId/Agdir.GlobalFieldId.csproj --configuration Release --output nupkg

    - name: Publish to NuGet
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: dotnet nuget push nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
